/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.autolavado.view;

import javax.swing.JOptionPane;

/**
 *
 * @author PC-21
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desk = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        mnuRol = new javax.swing.JCheckBoxMenuItem();
        mnuUsuario = new javax.swing.JCheckBoxMenuItem();
        mnuClientes = new javax.swing.JMenu();
        mnuCliente = new javax.swing.JCheckBoxMenuItem();
        mnuVehiculo = new javax.swing.JCheckBoxMenuItem();
        mnuServicios = new javax.swing.JMenu();
        mnuServicio = new javax.swing.JCheckBoxMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnuVenta = new javax.swing.JCheckBoxMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();
        Salir = new javax.swing.JCheckBoxMenuItem();

        setTitle("Sistema de aontrol autolavado");

        desk.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 153, 255));

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });

        mnuRol.setSelected(true);
        mnuRol.setText("Regustrar Rols");
        mnuRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRolActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuRol);

        mnuUsuario.setSelected(true);
        mnuUsuario.setText("Registrar Usuarios");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuUsuario);

        jMenuBar1.add(mnuUsuarios);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        mnuClientes.setText("Clientes");

        mnuCliente.setSelected(true);
        mnuCliente.setText("Registrar Cliente");
        mnuCliente.setToolTipText("");
        mnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuCliente);

        mnuVehiculo.setSelected(true);
        mnuVehiculo.setText("Registra Vehiculo");
        mnuVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVehiculoActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuVehiculo);

        jMenuBar1.add(mnuClientes);

        mnuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.png"))); // NOI18N
        mnuServicios.setText("Servicios");

        mnuServicio.setSelected(true);
        mnuServicio.setText("Registrar Servicios");
        mnuServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuServicioActionPerformed(evt);
            }
        });
        mnuServicios.add(mnuServicio);

        jMenuBar1.add(mnuServicios);

        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7.jpg"))); // NOI18N
        mnuVentas.setText("Ventas");

        mnuVenta.setText("Generar Venta");
        mnuVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentaActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuVenta);

        jMenuBar1.add(mnuVentas);

        mnuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8.png"))); // NOI18N
        mnuReportes.setText("Reportes");
        jMenuBar1.add(mnuReportes);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9.jpg"))); // NOI18N
        mnuSalir.setText("Salir");

        Salir.setSelected(true);
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        mnuSalir.add(Salir);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRolActionPerformed
        // TODO add your handling code here:
        FrmRol rol = new FrmRol();
        desk.add(rol);
        rol.setVisible(true);
    }//GEN-LAST:event_mnuRolActionPerformed

    private void mnuVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentaActionPerformed
        // TODO add your handling code here:
        FrmVenta venta = new FrmVenta();
        desk.add(venta);
        venta.setVisible(true);
    }//GEN-LAST:event_mnuVentaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
        FrmMenu.this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        // TODO add your handling code here:
        FrmUsuarios usuarios = new FrmUsuarios();
        desk.add(usuarios);
        usuarios.setVisible(true);
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClienteActionPerformed
        // TODO add your handling code here:
        FrmCliente cliente = new FrmCliente();
        desk.add(cliente);
        cliente.setVisible(true);
    }//GEN-LAST:event_mnuClienteActionPerformed

    private void mnuVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVehiculoActionPerformed
        // TODO add your handling code here:
        FrmVehiculo vehiculo = new FrmVehiculo();
        desk.add(vehiculo);
        vehiculo.setVisible(true);
    }//GEN-LAST:event_mnuVehiculoActionPerformed

    private void mnuServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuServicioActionPerformed
        // TODO add your handling code here:
        FrmServicio servicio = new FrmServicio();
        desk.add(servicio);
        servicio.setVisible(true);
    }//GEN-LAST:event_mnuServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Salir;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem mnuCliente;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JCheckBoxMenuItem mnuRol;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JCheckBoxMenuItem mnuServicio;
    private javax.swing.JMenu mnuServicios;
    private javax.swing.JCheckBoxMenuItem mnuUsuario;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JCheckBoxMenuItem mnuVehiculo;
    private javax.swing.JCheckBoxMenuItem mnuVenta;
    private javax.swing.JMenu mnuVentas;
    // End of variables declaration//GEN-END:variables
private void salir(){
    int opcion=JOptionPane.showConfirmDialog(null,
            "Seguro que deseas salir",
            "confirmar salida",
            JOptionPane.YES_NO_OPTION);
    if(opcion==JOptionPane.YES_OPTION){
        System.exit(0);
    }
}
}
